# -*- mode:yaml; coding: utf-8 -*-
language: python
cache: pip
sudo: required
dist: xenial
python:
  - 3.7
services:
  - docker
branches:
  only:
  - master
install:
  - 
script:
  - 
after_script:
  - 
